name = "photoz"
main = "src/worker.js"
compatibility_date = "2025-01-01"
account_id = "ede1e7633dd439375ff7a143c1c9b512"
keep_vars = true
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "photoz"
bucket_name = "photoz"
