name = "photoz"
main = "src/worker.js"
compatibility_date = "2026-05-29"
keep_vars = true # Preserve dashboard-managed secrets like PHOTOZ_ACCESS_CODE during wrangler deploy
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "photoz"
bucket_name = "photoz"
